#%RAML 1.0 DataType

type: object
properties: 
  firstName: 
    type: string
    required: false
  lastName:
    type: string
    required: false
  address: 
    type: string
    required: false
  postal: 
    type: string
    required: false
  country: 
    type: string
    required: false
  miles: 
    type: integer
    required: false
  type:
    type: string
    required: true
